### ISSUE TITLE
Error trying to build a native executable for Windows

### ISSUE THREAD

**Issue by blainjeremy** [ruby2d/ruby2d#157]
Hello,

I finally managed to build mruby (2.0.1) and got it working on Windows.
I am now trying to build a native executable for the triangle example from the docs.

Unfortunately, I am running into an error using a 'git bash' terminal :

```
Traceback (most recent call last):  
4: from C:/Ruby26-x64/bin/ruby2d:23:in `<main>'  
3: from C:/Ruby26-x64/bin/ruby2d:23:in `load'  
2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ruby2d-0.9.2/bin/ruby2d:85:in `<top (required)>'  
1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ruby2d-0.9.2/lib/ruby2d/cli/build.rb:99:in `build_native'  
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ruby2d-0.9.2/lib/ruby2d/cli/build.rb:99:in ``': No such file or directory - cc build/app.c -lmruby `simple2d --libs` -o build/app (Errno::ENOENT)
```

While this fails, it still generates these files in the build directory : app.c lib.c lib.rb src.c src.rb

-----

I get quiet the same error using 'powershell' or 'cmd' :

```
Traceback (most recent call last):  
4: from C:/Ruby26-x64/bin/ruby2d:23:in `<main>'  
3: from C:/Ruby26-x64/bin/ruby2d:23:in `load'  
2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ruby2d-0.9.2/bin/ruby2d:85:in `<top (required)>'  
1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ruby2d-0.9.2/lib/ruby2d/cli/build.rb:74:in `build_native'  
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ruby2d-0.9.2/lib/ruby2d/cli/build.rb:74:in ``': No such file or directory - which mruby (Errno::ENOENT)
```

Nothing is generated though, including the build directory.

**Comment by blainjeremy** [comment]
Since 'cc build/app.c -lmruby `simple2d --libs` -o build/app' seems to be the issue, i changed cc to gcc (which i have thanks to mingw).

Here is the error i now get from the same line :
gcc: error: `simple2d: No such file or directory
gcc: error: unrecognized command line option '--libs`'

Am I suppose to install simple2d myself or is it included with ruby2d?

**Comment by blacktm** [comment]
Hi @blainjeremy. Did you figure it out? Any code changes we could make to the gem? Would be great to get this working on Windows, and document it on the website.

**Comment by blainjeremy** [comment]
Yes I did make it work by installing simple2d (with a workaround though).
Now, I am at a point where I got an executable generated but it throws an error right when I launch it.

I will make a post (a bit later) explaining all the steps I followed up until now.

**Comment by blainjeremy** [comment]
Keep in mind this is pretty informal and some of the parts I describe might be trivial or quite rough!
Maybe I made some mistakes or had bad practices, please don't hesitate to point them out!

Depending on where you build/install the different tools needed, you might need to launch your command line tool "as Administrator".

I mention my own paths several times, so it obviously won't work without some tweaks for other people.
Windows is a bit tricky with spaces and paths (like "Program Files") so I tried to avoid them in paths for simplicity.
Paths also differ whether you use Powershell/cmd or a Bash environment (I use Git Bash for example), which sometimes adds some complexity/confusion :
 - Powershell/cmd : C:\Ruby25-x64\bin
 - Git Bash : /c/Ruby25-x64/bin

-----

Ruby & mingw
------------

I am using the Ruby installer 2.5.5-1 + devkit (msys/mingw64) (https://rubyinstaller.org/downloads/).
Run the installer, Ruby is installed first, then msys/mingw64 (I chose the 3rd option in the msys installation prompt).
Add <base_ruby_install_path>\bin to your PATH if not already present.
Then, also add <base_ruby_install_path>\msys64\mingw64\bin to your PATH (the order in your PATH might be important here if you already have another mingw installed, not quite sure though).

-----

mruby
-----

mruby relies on bison (http://gnuwin32.sourceforge.net/packages/bison.htm)
Download the "Complete package, except sources" setup file (http://downloads.sourceforge.net/gnuwin32/bison-2.4.1-setup.exe).
Run the installer and add <base_bison_install_path>\bin to your PATH.

Download the sources for mruby (https://github.com/mruby/mruby/releases).
Be careful here! I had an error later when trying to build the game's executable that leads me to think that the directory where you build mruby is important (I suspect mruby to generate absolute paths in its files, not relative ones).
So, for safety, I extracted the archive in the directory I intended mruby to stay (C:\mruby-2.0.1 for example) and built it from there.

Follow the mruby instructions to build it (for me it was just running "./minirake", that's it).
Add <base_mruby_install_path>\bin to your PATH.
You can run "mruby --version" or "./minirake test" to check there are no errors.

Now that we have all the prerequisites, we can move on to building the executable (next part tomorrow).

**Comment by blainjeremy** [comment]
Quick update as I finally got the executable running for the triangle example.
I had to use some ugly techniques to make it work, but it's still better than nothing for now i guess...
Anyway, I will post the second part tomorrow as promise!

**Comment by blainjeremy** [comment]
This post will be a bit messy as I tried a lot of things along the way and I don't remember precisely in which order everything happened.

Building the executable
-----------------------

After installing the ruby2d gem, I ran "ruby2d build --native triangle.rb" to build the executable.

The first error I got only occured with Powershell/cmd :
```
Traceback (most recent call last):
        4: from C:/Ruby25-x64/bin/ruby2d:23:in `<main>'
        3: from C:/Ruby25-x64/bin/ruby2d:23:in `load'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.9.2/bin/ruby2d:85:in `<top (required)>'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.9.2/lib/ruby2d/cli/build.rb:74:in `build_native'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.9.2/lib/ruby2d/cli/build.rb:74:in ``': No such file or directory - which mruby (Errno::ENOENT)
```

This build.rb file (located in the gem) will be key for the rest of this post so I will just refer to it as build.rb from now on.
All the errors and "fixes" I made were in the build_native method (line 70).
My understanding is that this method is supposed to be cross-platform but after my "fixes" I don't think it will work outside Windows.

Back to the error : the "which" command cannot be found by Powershell/cmd as it is a Windows environment. It does work with Git Bash though.
That will probably be a trend for the rest of this post, but, to be honest, my "fixes" are just ugly/clunky/awkward (you name it) solutions, as my first goal was to get this whole thing working, so sorry about that...

Since I already knew mruby was working, I just commented out the whole if statement (lines 74-77) to make it work with Powershell/cmd.

simple2d
--------

I ran the build again :
```
cc: error: `simple2d: No such file or directory
cc: error: unrecognized command line option '--libs`'
```

First, to get that out of the way, the "cc" command will not work so I replaced it with "gcc" (line 90).

Then, all the command line tools I used seemed to struggle with this nested backquotes commands (line 90).
I tried to put the result of "simple2d --libs" in a variable and interpolate it but without success (I am new to Ruby and stuffs, that may be why...).

I tried to run "simple2d --libs" by itself but had no executable for it.
I think simple2d (and potentially its executable) is somewhere inside the gem, yet I only found simple2d.h and other related include/lib files.
So I tried to install it myself (https://github.com/simple2d/simple2d/releases/tag/v1.1.0) and used the mingw version.

I could finally launch the command and saw it resulted in just all the necessary headers and/or libraries needed to build the executable :
`-I/usr/local/include/ -L/usr/local/lib -lmingw32 -lsimple2d -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lopengl32 -lglew32`
This result comes when executing from Git Bash, I got a totally different result with Powershell/cmd though...
At this point, I decided to stick only with Git Bash as this is my tool of choice and I was already struggling enough with one command line tool...

So, I decided to change the nested backquotes line in build.rb and to hardcode the needed libraries instead (remember, I was just trying to make it work)...
`gcc build/app.c -lmruby -I/usr/local/include/ -L/usr/local/lib -lmingw32 -lsimple2d -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lopengl32 -lglew32 -o build/app`
The /usr/local/include|lib comes from the installation of simple2d and these actually are directories inside the Git Bash installation folder :
`C:\Program Files\Git\usr\local`
I don't remember the thought process that led me to that but at this point, I just copied the lib and include directories from the simple2d archive straight into my triangle example directory, alongside triangle.rb, as I had this recurring error I couldn't get rid of :
```
build/app.c:2255:12: fatal error: simple2d.h: No such file or directory
   #include <simple2d.h>
            ^~~~~~~~~~~~
compilation terminated.
```

Line 90 in build.rb now looks like this :
`gcc build/app.c -lmruby -Iinclude -Llib -lmingw32 -lsimple2d -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lopengl32 -lglew32 -o build/app`
Again, the include and lib directory from the simple2d archive are now next to triangle.rb.

All simple2d errors are now finally gone.

mruby
-----

I ran the build again :
```
build/app.c:2260:12: fatal error: mruby.h: No such file or directory
   #include <mruby.h>
            ^~~~~~~~~
compilation terminated.
```

To make things short and for the same reasons as simple2d, I decided to copy two more directories (from mruby this time) into the triangle project folder :
<mruby_install_path>/include
<mruby_install_path>/build/host/lib

Building the executable again :
```
lib/libmruby.a(io.o): In function `fptr_finalize':
C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:664: undefined reference to `__imp_closesocket'
C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:665: undefined reference to `__imp_WSAGetLastError'
C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:664: undefined reference to `__imp_closesocket'
C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:665: undefined reference to `__imp_WSAGetLastError'
lib/libmruby.a(io.o): In function `mrb_io_s_select':
C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:1154: undefined reference to `__imp_select'
C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:1179: undefined reference to `__WSAFDIsSet'
C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:1190: undefined reference to `__WSAFDIsSet'
C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:1202: undefined reference to `__WSAFDIsSet'
C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:1192: undefined reference to `__WSAFDIsSet'
C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:1204: undefined reference to `__WSAFDIsSet'
lib/libmruby.a(io.o):C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:1180: more undefined references to `__WSAFDIsSet' follow
lib/libmruby.a(io.o): In function `fptr_finalize':
C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:664: undefined reference to `__imp_closesocket'
C:/mruby-2.0.1/mrbgems/mruby-io/src/io.c:665: undefined reference to `__imp_WSAGetLastError'
collect2.exe: error: ld returned 1 exit status
```

After some research, this is caused by a missing library (-lws2_32), here is the new line 90 in build.rb :
`gcc build/app.c -lmruby -lws2_32 -Iinclude -Llib -lmingw32 -lsimple2d -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lopengl32 -lglew32 -o build/app`

Finally, we have an executable in our hands!

Launching the game
------------------

I launched the executable :
ArgumentError: non-absolute home

After some research and testing, it comes from <mruby_install_path>/mrbgems/mruby-io/src/file.c (line 325).
The issue was that USERPROFILE seemed to be set to a relative path (I am not quite sure it was set at all in the first place to be honest), but after many tries to change it to an absolute path, I still got the error...

So I took a radical approach once again, by commenting out line 324 to 326, just to see what happens...

To test the changes, delete the build and bin directories inside <mruby_install_path> and run "./minirake" again from there (looong build).
When finished, copy <mruby_install_path>/build/host/lib inside the triangle.rb directory once again.

And now, when we rebuild and launch the game, our triangle should appear!
There is also a (console) window that opens alongside the regular ruby2d window when I launch the executable from the file explorer...

So, I don't know what that means that we commented out the part using USERPROFILE and what side effects this could have...
But setting USERPROFILE to the right value should take care of this potential issue, I just didn't find it...

Alright, that's it for me, I hope all this mess will still help a little bit!

**Comment by blacktm** [comment]
Thanks for sharing all this detail @blainjeremy! I think we can definitely use it to build a Windows compilation path in the gem.

**Comment by nightblade9** [comment]
It looks like building/running on Windows is still broken. I appear to be running into exactly the same steps. This is very problematic. The documentation is also out of date; it just mentions TBD (doesn't even mention the command has changed to `ruby2d build --native`.

Are there any plans to improve this?

**Comment by blacktm** [comment]
Building natively should all be fixed in 9650c7b3c9811bd17d2c6e6205d5660cc9dbf788!
