### ISSUE TITLE
Building a native executable fails with the wrong message when mruby is not installed

### ISSUE THREAD

**Issue by nightblade9** [ruby2d/ruby2d#162]
Repro steps (tested on Windows):

- Install the ruby2d gem
- Build a simple app
- Forget to install `mruby`
- Run `ruby2d build --native main.rb`

Expected: the error message from [line 75](https://github.com/ruby2d/ruby2d/blob/43ce9805a7ae8b82b7ab8c50bf6d4c845d395dc4/lib/ruby2d/cli/build.rb#L74)

Actual: `build.rb` fails on line 74 with this stack-trace:

```
Traceback (most recent call last):
        4: from D:/Ruby25-x64/bin/ruby2d:23:in `<main>'
        3: from D:/Ruby25-x64/bin/ruby2d:23:in `load'
        2: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.9.2/bin/ruby2d:85:in `<top (required)>'
        1: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.9.2/lib/ruby2d/cli/build.rb:74:in `build_native'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.9.2/lib/ruby2d/cli/build.rb:74:in ``': No such file or directory - which mruby (Errno::ENOENT)
```

The stack is pretty clear about what the problem is.

**Comment by blacktm** [comment]
Building should be fixed in 9650c7b3c9811bd17d2c6e6205d5660cc9dbf788.
