### ISSUE TITLE
cannot load such file -- ruby2d (LoadError)

### ISSUE THREAD

**Issue by fguillen** [ruby2d/ruby2d#230]
I see an error just when I do `require "ruby2d"`

```
<internal:/Users/user/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': dlopen(/Users/user/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ruby2d-0.11.1/lib/ruby2d/ruby2d.bundle, 9): Symbol not found: _CHHapticDynamicParameterIDHapticIntensityControl (LoadError)
  Referenced from: /Users/user/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ruby2d-0.11.1/lib/ruby2d/ruby2d.bundle
  Expected in: flat namespace
 in /Users/user/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ruby2d-0.11.1/lib/ruby2d/ruby2d.bundle - /Users/user/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ruby2d-0.11.1/lib/ruby2d/ruby2d.bundle
	from <internal:/Users/user/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/user/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ruby2d-0.11.1/lib/ruby2d.rb:33:in `<top (required)>'
	from <internal:/Users/user/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/Users/user/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/Users/user/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from game.rb:1:in `<main>'
<internal:/Users/user/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- ruby2d (LoadError)
	from <internal:/Users/user/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from game.rb:1:in `<main>'

```

OS: Mac Catalina 10.15.5
Ruby: 3.0.1p64

The gem is installed:

> gem list | grep ruby2d
ruby2d (0.11.1)

**Comment by AndyObtiva** [comment]
Similar system (Mac Catalina 10.5.7), same error (tried in Ruby 3.1.0, Ruby 2.7.2, and Ruby 2.6.2):

```
Successfully installed ruby2d-0.11.1
1 gem installed
andymaleh@Andys-MacBook-Pro-13 flappy_bird % ruby main.rb 
Traceback (most recent call last):
	2: from main.rb:3:in `<main>'
	1: from /Users/andymaleh/.rvm/rubies/ruby-2.6.2/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/andymaleh/.rvm/rubies/ruby-2.6.2/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ruby2d (LoadError)
	6: from main.rb:3:in `<main>'
	5: from /Users/andymaleh/.rvm/rubies/ruby-2.6.2/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	4: from /Users/andymaleh/.rvm/rubies/ruby-2.6.2/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	3: from /Users/andymaleh/.rvm/rubies/ruby-2.6.2/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	2: from /Users/andymaleh/.rvm/gems/ruby-2.6.2@flappy_bird/gems/ruby2d-0.11.1/lib/ruby2d.rb:33:in `<top (required)>'
	1: from /Users/andymaleh/.rvm/rubies/ruby-2.6.2/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/andymaleh/.rvm/rubies/ruby-2.6.2/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/andymaleh/.rvm/gems/ruby-2.6.2@flappy_bird/gems/ruby2d-0.11.1/lib/ruby2d/ruby2d.bundle, 9): Symbol not found: _CHHapticDynamicParameterIDHapticIntensityControl (LoadError)
  Referenced from: /Users/andymaleh/.rvm/gems/ruby-2.6.2@flappy_bird/gems/ruby2d-0.11.1/lib/ruby2d/ruby2d.bundle
  Expected in: flat namespace
 in /Users/andymaleh/.rvm/gems/ruby-2.6.2@flappy_bird/gems/ruby2d-0.11.1/lib/ruby2d/ruby2d.bundle - /Users/andymaleh/.rvm/gems/ruby-2.6.2@flappy_bird/gems/ruby2d-0.11.1/lib/ruby2d/ruby2d.bundle
```

I even tried installing the Simple2D library thinking it was required, but that did not help.

Does ruby2d require Simple2D to be installed or can it work for some games without Simple2D?

**Comment by blacktm** [comment]
Hi @fguillen and @AndyObtiva, unfortunately macOS 10 doesn't have the new APIs needed by SDL which added haptics (like controller rumble, all in the [Game Controller and Core Haptics frameworks](https://developer.apple.com/videos/play/wwdc2020/10614)) so we'll have to restrict to macOS 11.0+. We can leave this issue open as a reminder to add a version check to let people know on install. Sorry for the trouble here!
