### ISSUE TITLE
symbol not found in flat namespace '_objc_msgSend$CGLContextObj' when require 'ruby2d'

### ISSUE THREAD

**Issue by mahdiarn** [ruby2d/ruby2d#274]
Issue happened on:

ruby2d 0.12.1
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
OS: macos 12.4 silicon

code:
main.rb
```
require 'ruby2d'

set title: "Hello Triangle"

Triangle.new(
  x1: 320, y1:  50,
  x2: 540, y2: 430,
  x3: 100, y3: 430,
  color: ['red', 'green', 'blue']
)

show
```

Issue trigger:

run ruby main.rb

Error log when exception raised:

```
<internal:/Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': dlopen(/Users/username/.rvm/gems/ruby-3.1.2/gems/ruby2d-0.12.1/lib/ruby2d/ruby2d.bundle, 0x0009): symbol not found in flat namespace '_objc_msgSend$CGLContextObj' - /Users/username/.rvm/gems/ruby-3.1.2/gems/ruby2d-0.12.1/lib/ruby2d/ruby2d.bundle (LoadError)
	from <internal:/Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/username/.rvm/gems/ruby-3.1.2/gems/ruby2d-0.12.1/lib/ruby2d/core.rb:31:in `<top (required)>'
	from <internal:/Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/username/.rvm/gems/ruby-3.1.2/gems/ruby2d-0.12.1/lib/ruby2d.rb:3:in `<top (required)>'
	from <internal:/Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from main.rb:1:in `<main>'
<internal:/Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- ruby2d (LoadError)
	from <internal:/Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from main.rb:1:in `<main>'
```

**Comment by blacktm** [comment]
Hopefully fixed now!
