### ISSUE TITLE
Exception when using Text on a pc with no default audio device.

### ISSUE THREAD

**Issue by amreus** [ruby2d/ruby2d#276]
Ruby2d 0.12.1
Windows 10 Home
Ruby 3.1.3p185
cmd.exe 

Here is the basic program:

```ruby
require 'ruby2d'
update do
    Text.new("Hello")
end
show
```

I mostly use bluetooth for audio on this Windows 10 PC, but when there is no default audio device there is the following exception.  The exception also goes away when I just plug some headphones in the jack. 

And the exception in the console:

```
Error: (Mix_OpenAudio) WASAPI can't find requested audio endpoint: Element not found.
(this repeats hundreds of times)
Error: (Mix_OpenAudio) WASAPI can't find requested audio endpoint: Element not found.
Error: (Mix_OpenAudio) WASAPI can't find requested audio endpoint: Element not found.
Error: (Mix_OpenAudio) WASAPI can't find requested audio endpoint: Element not found.
Error: (SDL_Init) Haptic: SubSystem already open.
Error: (SDL_Init) Haptic: SubSystem already open.
C:/Users/Amreus/.gem/ruby/3.1.0/gems/ruby2d-0.12.1/lib/ruby2d/texture.rb:26:in `ext_create': wrong argument type nil (expected Data) (TypeError)
        from C:/Users/Jim/.gem/ruby/3.1.0/gems/ruby2d-0.12.1/lib/ruby2d/texture.rb:26:in `draw'
        from C:/Users/Jim/.gem/ruby/3.1.0/gems/ruby2d-0.12.1/lib/ruby2d/text.rb:88:in `render'
        from C:/Users/Jim/.gem/ruby/3.1.0/gems/ruby2d-0.12.1/lib/ruby2d/window.rb:474:in `ext_show'
        from C:/Users/Jim/.gem/ruby/3.1.0/gems/ruby2d-0.12.1/lib/ruby2d/window.rb:474:in `show'
        from C:/Users/Jim/.gem/ruby/3.1.0/gems/ruby2d-0.12.1/lib/ruby2d/dsl.rb:45:in `show'
        from C:/Users/Jim/tmp/r2d.rb:7:in `<main>'
```

If it would help, let me know if I can provide more info, or run some tests or anything. Thanks.

**Comment by blacktm** [comment]
Hopefully fixed now. If there's no default audio device, it might fail to install, so we'd have to rely on SDL3's `dummy` device. We'll see if that's needed though!
