### ISSUE TITLE
Error installing on Windows - cannot find -lSDL2main

### ISSUE THREAD

**Issue by jjgh** [ruby2d/ruby2d#28]
Hi, thanks for this library!

I am having problem installing it on Windows 7 64 bit.
My Ruby environment:

> ruby -v
`ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]`

Devkit is installed and working.
I installed simple2d libraries following the Getting Started guide on Ruby2d website.

But when I try to run `gem install ruby2d` this is what I get:

```
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing ruby2d:
        ERROR: Failed to build gem native extension.

    current directory: C:/dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/ext/ruby2d
C:/dev/ruby/Ruby23-x64/bin/ruby.exe -r ./siteconf20170324-1716-1angnxw.rb extconf.rb
creating Makefile

current directory: C:/dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/ext/ruby2d
make "DESTDIR=" clean

current directory: C:/dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/ext/ruby2d
make "DESTDIR="
generating ruby2d-x64-mingw32.def
compiling ruby2d.c
In file included from c:/dev/ruby/Ruby23-x64/include/ruby-2.3.0/ruby/win32.h:41:0,
                 from c:/dev/ruby/Ruby23-x64/include/ruby-2.3.0/ruby/defines.h:168,
                 from c:/dev/ruby/Ruby23-x64/include/ruby-2.3.0/ruby/ruby.h:36,
                 from c:/dev/ruby/Ruby23-x64/include/ruby-2.3.0/ruby.h:33,
                 from ruby2d.c:16:
c:\dev\ruby\ruby-devkit-64-4.7.2\mingw\bin\../lib/gcc/x86_64-w64-mingw32/4.7.2/../../../../x86_64-w64-mingw32/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
ruby2d.c: In function 'ruby2d_image_init':
ruby2d.c:159:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c: In function 'ruby2d_sprite_init':
ruby2d.c:193:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c: In function 'ruby2d_text_init':
ruby2d.c:226:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c: In function 'ruby2d_text_equals':
ruby2d.c:252:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c: In function 'ruby2d_sound_init':
ruby2d.c:288:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c: In function 'ruby2d_music_init':
ruby2d.c:337:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c: In function 'render':
ruby2d.c:500:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c:587:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c:592:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c:628:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c: In function 'ruby2d_show':
ruby2d.c:657:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c:678:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c: In function 'Init_ruby2d':
ruby2d.c:740:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c:746:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c:755:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c:764:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
ruby2d.c:785:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
linking shared-object ruby2d/ruby2d.so
c:/dev/ruby/ruby-devkit-64-4.7.2/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.7.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lSDL2main
collect2.exe: error: ld returned 1 exit status
make: *** [ruby2d.so] Error 1

make failed, exit code 2
```

I hope it's something that can be fixed soon!  Because Ruby's world desperately needs a stable, cross-platform library for working with graphics and audio! :)
Thanks a lot!

**Comment by blacktm** [comment]
Hi there, glad you like the project!

D'oh, thanks for flagging. Looks like a simple config fix, I hope. And I agree — getting this library to work everywhere consistently is quite important, albeit a challenge sometimes. I'll report back soon.

**Comment by blacktm** [comment]
Made a few Windows / MinGW fixes in 5247c3caa0091a77cce772de30cd44aaff484e16, so everything should now work as expected. I don't have a new version of the gem pushed up yet, but you can still get the latest version up and running by first cloning this repo with `git clone --recursive https://github.com/ruby2d/ruby2d.git` and running `rake`. Give the test card a try by running `rake test:mri testcard`

Let me know if you have any other issues. Thanks!

**Comment by jjgh** [comment]
Hi, thanks for working on it!
Unfortunately I am not experiencing in building gems... anyway I cloned the repo and gave it a try, but I got this:

```
C:\Users\xxx\Downloads\ruby2d\ruby2d [master]> rake
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
C:/Users/xxx/Downloads/ruby2d/ruby2d/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
C:\Users\xxx\Downloads\ruby2d\ruby2d [master]>
```

I think it's a issue with how Window Git Shell sees my Ruby environment... but honestly I don't want to steal more of your time and at the same time I don't want to delve too deep into this myself :)
I think I'll just wait for the gem and the report back :)
Maybe - I'm just suggesting - you could re-open this issue as a note to yourself, for letting Windows people know when the new build is available? ;) Or, I'll just come and check now and then.
Thanks a lot!

**Comment by blacktm** [comment]
Oh, that error is just a confusing way of saying the `rspec` gem isn't installed. A `bundle install` should fix that.

I'd rather not have a broken gem hanging out there, so I created a [new release branch](https://github.com/ruby2d/ruby2d/commits/v0.3.1) from v0.3.0 and just applied the Windows fixes in 5247c3caa0091a77cce772de30cd44aaff484e16. Before pushing this new version of the gem, could you give it a try locally and confirm it works? Here are the commands in order to do that:

```bash
git clone --recursive https://github.com/ruby2d/ruby2d.git
cd ruby2d
git checkout v0.3.1
gem install bundler
bundle install
rake  # build the gem and run unit tests
rake test:mri testcard  # run the test card just to make things looks correct
```

Thanks so much!

**Comment by jjgh** [comment]
Thanks a lot for the instructions, but no luck yet:

```
C:\Users\xxx\Downloads\ruby2d [master]> git checkout v0.3.1

M       assets
Branch v0.3.1 set up to track remote branch v0.3.1 from origin.
Switched to a new branch 'v0.3.1'

C:\Users\xxx\Downloads\ruby2d [v0.3.1 +0 ~1 -0]> gem install bundler

Successfully installed bundler-1.14.6
Parsing documentation for bundler-1.14.6
Done installing documentation for bundler after 2 seconds
1 gem installed
C:\Users\xxx\Downloads\ruby2d [v0.3.1 +0 ~1 -0]> bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using concurrent-ruby 1.0.5
Installing diff-lcs 1.3
Using hike 1.2.3
Using sourcemap 0.1.1
Using rack 2.0.1
Using tilt 2.0.7
Installing rspec-support 3.5.0
Using bundler 1.14.6
Using sprockets 3.7.1
Installing rspec-core 3.5.4
Installing rspec-expectations 3.5.0
Installing rspec-mocks 3.5.0
Using opal 0.10.3
Installing rspec 3.5.0
Using ruby2d 0.3.0 from source at `.`
Bundle complete! 2 Gemfile dependencies, 15 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

C:\Users\xxx\Downloads\ruby2d [v0.3.1 +0 ~1 -0]> rake

rake aborted!
Errno::ENOENT: No such file or directory - which simple2d
C:/Users/xxx/Downloads/ruby2d/Rakefile:14:in ``'
C:/Users/xxx/Downloads/ruby2d/Rakefile:14:in `<top (required)>'
(See full trace by running task with --trace)

```

**Comment by blacktm** [comment]
Hmm, not sure why `which simple2d` is failing in the Rakefile, but at any rate, could you try building and running the gem manually with:

```bash
gem build ruby2d.gemspec --verbose
gem install ruby2d-0.3.0.gem --local --verbose

# Run testcard
cd test
ruby testcard.rb
```

**Comment by jjgh** [comment]
Output for above commands:

```


c:\Users\xxx\Downloads\ruby2d>gem build ruby2d.gemspec --verbose
  Successfully built RubyGem
  Name: ruby2d
  Version: 0.3.0
  File: ruby2d-0.3.0.gem

c:\Users\xxx\Downloads\ruby2d>gem install ruby2d-0.3.0.gem --local --verbose
Temporarily enhancing PATH to include DevKit...
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/assets/README.md
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/assets/app.icns
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/assets/opal.js
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/assets/simple2d.js
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/assets/template.html
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/bin/ruby2d
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/ext/ruby2d/extconf.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/ext/ruby2d/ruby2d-opal.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/ext/ruby2d/ruby2d.c
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/application.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/color.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/dsl.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/exceptions.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/image.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/music.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/quad.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/rectangle.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/sound.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/sprite.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/square.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/text.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/triangle.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/version.rb
C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/window.rb
Building native extensions.  This could take a while...
current directory: C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/ext/ruby2d
C:/Dev/ruby/Ruby23-x64/bin/ruby.exe -r ./siteconf20170405-6596-orsm17.rb extconf.rb
which: no simple2d in (.; C:\Dev\ruby\Ruby-DevKit-64-4.7.2\bin; C:\Dev\ruby\Ruby-DevKit-64-4.7.2\mingw\bin; c:\Dev\ruby\Ruby-DevKit-64-4.7.2\bin; c:\Dev\ruby\Ruby-DevKit-64-4.7.2\mingw\bin; C:\Dev\ruby\Ruby23-x64\bin; C:\Program Files (x86)\Intel\iCLS Client\; C:\Program Files\Intel\iCLS Client\; C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common; C:\dev\Python\Python34\; C:\dev\Python\Python34\Scripts; C:\ProgramData\Oracle\Java\javapath; C:\Windows\system32; C:\Windows; C:\Windows\System32\Wbem; C:\Windows\System32\WindowsPowerShell\v1.0\; C:\Program Files (x86)\Pinnacle\Shared Files\; C:\Program Files (x86)\GtkSharp\2.12\bin; C:\Program Files\Microsoft SQL Server\120\Tools\Binn\; C:\Program Files (x86)\nodejs\; C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\; C:\Program Files\Microsoft SQL Server\130\Tools\Binn\; C:\Program Files\Common Files\Autodesk Shared\; C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL; C:\Program Files\Intel\Intel(R) Management Engine Components\DAL; C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT; C:\Program Files\Intel\Intel(R) Management Engine Components\IPT; C:\dev\ruby\Ruby23-x64\bin; C:\dev\jruby-9.0.0.0\bin; C:\Dev\curl-7.28; C:\Program Files (x86)\Bitvise SSH Client; C:\toolsinpath; C:\Users\xxx\AppData\Roaming\npm; C:\ProgramFiles (x86)\Nmap)

== Ruby 2D Installation Errors =====================================

  Ruby 2D uses a native library called Simple 2D.

  To install Simple 2D, follow the instructions in the README:
    https://github.com/simple2d/simple2d

====================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Dev/ruby/Ruby23-x64/bin/$(RUBY_BASE_NAME)
ERROR:  Error installing ruby2d-0.3.0.gem:
        ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
extconf failed, exit code 1

Gem files will remain installed in C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0 for inspection.
Results logged to C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/ruby2d-0.3.0/gem_make.out

c:\Users\xxx\Downloads\ruby2d>

```

**Comment by blacktm** [comment]
Ok, that would be why the `which` command failed. I should probably amend the [Ruby 2D on Windows](http://www.ruby2d.com/learn/windows/) guide with instructions on _permanently_ setting the path (closing the command prompt will clear them in the current guidance).

Looks like your path is also missing `/usr/local/bin`, which you can add temporarily in your case using: `set PATH=%PATH%;c:\Dev\ruby\Ruby-DevKit-64-4.7.2\local\bin`. And if you don't yet have Simple 2D installed, you can follow [these instructions](http://www.ruby2d.com/learn/windows/#installing-simple-2d). And that's it, should work.

I can already think of a few things to change, but if you have any feedback on the windows guide, let me know. It might not be possible to fully automate the install and configuration process, but we can provide clear instructions instead. Thanks!

**Comment by jjgh** [comment]
Ok, adding `/usr/local/bin` to the path I could finally install the gem with native extensions.
I then ran `rake test:mri testcard` and the graphics window shows up, and everything seems to be fine with console output:

```
c:\Users\xxx\Downloads\ruby2d\test>rake test:mri testcard
(in c:/Users/xxx/Downloads/ruby2d)

==> Running MRI test: testcard.rb

=== Window Attributes ===
Title: Ruby 2D â?" Test Card
Background: #<Ruby2D::Color:0x00000002bd0a40>
Width:  700
Height: 500
Window: #<Ruby2D::Window:0x00000002bd0ae0>

Info: Controllers detected: 2
Info: Controller #0 (generic): VJoy Virtual Joystick
      Axes: 8
      Buttons: 32
      Balls: 0
Info: Controller #1 (generic): VJoy Virtual Joystick
      Axes: 8
      Buttons: 32
      Balls: 0
Info: OpenGL Context
      GL_VENDOR: Intel
      GL_RENDERER: Intel(R) HD Graphics 630
      GL_VERSION: 3.3.0 - Build 21.20.16.4508
      GL_SHADING_LANGUAGE_VERSION: 3.30 - Build 21.20.16.4508
Mouse down at: 225, 162
Mouse down at: 145, 197
Mouse down at: 109, 155
Mouse down at: 155, 139
```

Nice to see it working! Thanks for your support!

What I think it was happening is that while I was going along with the installation guide, I was initially using the Ruby command prompt (“Start Command Prompt with Ruby) and I had correctly added `/usr/local/bin` to the path, but then I switched to the Git Shell Windows utility to clone the repo, and then carried on from there trying to build the gem, missing the `/usr/local/bin` addition to the path... ! My bad!

Anyway, that tricked me in my case, but maybe it could still be nice to make it more explicit in the guide that users will have to keep executing commands in the same Ruby command prompt they opened before. I know that adding `/urs/local/bin` to that makes it a bit self explanatory that you should keep using it, but the way the guide is divided at that point could still trick inattentive people like me into thinking that the next steps are not tightly related :)

Thanks again and all the best to ruby2d!

**Comment by jjgh** [comment]
Just wanted to add that even now that the gem is installed, it only works if I do `set PATH=%PATH%;c:\Dev\ruby\Ruby-DevKit-64-4.7.2\local\bin` before launching the Ruby script, otherwise I get:

```
C:\Users\xxx\Downloads>ruby ruby2d-hello.rb
C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': 126: Can't find module.   - C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d/ruby2d.so (LoadError)
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby2d-0.3.0/lib/ruby2d.rb:17:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from ruby2d-hello.rb:1:in `<main>'
```

This also happens if I launch the script from a Ruby command prompt.

**Comment by blacktm** [comment]
Glad to hear it works. Just pushed a [new release](https://github.com/ruby2d/ruby2d/releases/tag/v0.3.1) with the fix. I'll try to make the guide a bit more clear — thanks for the feedback. Regarding the `/usr/local/bin`, this needs to be in your path to run Ruby 2D apps. `set PATH=...` only does this temporarily, so looks like `setx PATH "%PATH%;c:\Dev\ruby\Ruby-DevKit-64-4.7.2\local\bin"` will do that permanently. Another thing to add to the guide.
